// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RN-On29ZQbW5tvVPVhqYKPefPumU64A',
    appId: '1:576070748804:web:e8a56b37e56d7e073a90d1',
    messagingSenderId: '576070748804',
    projectId: 'runfitapp-57a83',
    authDomain: 'runfitapp-57a83.firebaseapp.com',
    storageBucket: 'runfitapp-57a83.firebasestorage.app',
    measurementId: 'G-ZLZLKX6CJP',
    databaseURL: 'https://runfitapp-57a83-default-rtdb.firebaseio.com', // <--- ADICIONE/VERIFIQUE ESTA LINHA
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxScEr5IMTu0gOXY66TiI_St3V78jK7g',
    appId: '1:576070748804:android:6a2ece8778ec547e3a90d1',
    messagingSenderId: '576070748804',
    projectId: 'runfitapp-57a83',
    storageBucket: 'runfitapp-57a83.firebasestorage.app',
    databaseURL: 'https://runfitapp-57a83-default-rtdb.firebaseio.com', // <--- ADICIONE/VERIFIQUE ESTA LINHA
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ5iJHvz9u8h-QSnqx3Y4-pYni_MZ4lpg',
    appId: '1:576070748804:ios:a360107c255980e23a90d1',
    messagingSenderId: '576070748804',
    projectId: 'runfitapp-57a83',
    storageBucket: 'runfitapp-57a83.firebasestorage.app',
    iosBundleId: 'com.example.runfitApp',
    databaseURL: 'https://runfitapp-57a83-default-rtdb.firebaseio.com', // <--- ADICIONE/VERIFIQUE ESTA LINHA
  );
}